import React from 'react';
import { Sparkles, Brain, Cpu, CheckCircle2, TrendingUp, ArrowUpRight } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { AIRecommendations } from '../components/dashboard/AIRecommendations';
import { Badge } from '../components/common/Badge';
import { Button } from '../components/common/Button';

export function Recommendations() {
  const { recommendations, executeRecommendation, isLoading } = useStore();

  return (
    <div className="dashboard-container">
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <Sparkles size={24} color="var(--cyan)" />
          <h1 className="greeting-title" style={{ fontSize: 22 }}>Autonomous AI Recommendations</h1>
        </div>
        <p className="greeting-subtitle">
          Real-time decisions generated by store computer vision, queue kinematics, and predictive demand models.
        </p>
      </div>

      {/* Main AI Recommendations Cards */}
      <AIRecommendations />

      {/* Explainable AI Decision Engine Details */}
      <div className="card">
        <div className="card-header-row">
          <div>
            <div className="card-title">
              <Brain size={18} color="var(--cyan)" />
              <span>Explainable AI Model Architecture</span>
            </div>
            <div className="card-subtitle">Telemetry reasoning and confidence weights</div>
          </div>
          <Badge variant="cyan">Deep Vision v4</Badge>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16, marginTop: 16 }}>
          <div style={{ padding: 14, background: 'var(--bg-surface)', borderRadius: 8, border: '1px solid var(--border-subtle)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-white)', marginBottom: 6 }}>
              1. Shelf Vision Telemetry
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              Overhead shelf cameras analyze depth maps and optical density to estimate remaining product units with &gt;95% precision.
            </p>
          </div>

          <div style={{ padding: 14, background: 'var(--bg-surface)', borderRadius: 8, border: '1px solid var(--border-subtle)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-white)', marginBottom: 6 }}>
              2. Queue Kinematics Model
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              Detects queue length, cart volumes, and cashier item scan velocity to forecast queue breaches before customers become frustrated.
            </p>
          </div>

          <div style={{ padding: 14, background: 'var(--bg-surface)', borderRadius: 8, border: '1px solid var(--border-subtle)' }}>
            <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-white)', marginBottom: 6 }}>
              3. Dynamic Demand Forecast
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
              Fuses historical hourly footfall patterns, local weather, and day-of-week seasonality to predict exact hourly unit sales.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
